### ISSUE TITLE
upload file too big

### ISSUE THREAD

**Issue by Khyretos** [linuxserver/docker-xbackbone#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When uploading a file of 8GB to my docker instance i get the 413 error.
i tried to edit the nginx.conf file but saw that the client_max body_size parameter was set to 0

### Expected Behavior

the file should upload without presenting any errors or problems

### Steps To Reproduce

1. go to the upload page
2. upload a file of 8gb or higher
3.  open developer tools and see the error

### Environment

```markdown
- OS: Ubuntu server
- How docker service was installed: docker compose up -d
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
using keys found in /config/keys
ln: failed to create symbolic link '/app/www/public/config.php': File exists
ln: failed to create symbolic link '/app/www/public/storage/storage': File exists
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by Khyretos** [comment]
![image](https://user-images.githubusercontent.com/25864917/233496822-ff7a34e7-5908-45bf-a241-b5b126b703dc.png)

**Comment by Khyretos** [comment]
i dont know why my issue was marked as invalid but here is video proof:

https://user-images.githubusercontent.com/25864917/233501790-9e046cbf-6c9c-4308-935e-54ef0dcf5030.mp4

i dont see anything in the logs, the error only appears in the developer tools of the browser

**Comment by j0nnymoe** [comment]
I marked it invalid because you haven't provided full container logs nor your docker-compose. Also I think it might be helpful if we knew the specs of your host.

**Comment by Khyretos** [comment]
Docker compose file:
```yaml
version: "2.1"
services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone:latest
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/Data/Services/xbackbone/app:/config
    #ports:
      #- 80:80
      #- 443:443
    expose:
      - 80
      - 443
    restart: unless-stopped
```
i do not assign it to a port specifically because i connect it to my nginx reverse proxy

log from portainer:

```[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
ln: failed to create symbolic link '/app/www/public/config.php': File exists
ln: failed to create symbolic link '/app/www/public/storage/storage': File exists
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

Host specs:
* HP ProDesk 400 G1 SFF (J8T18EA#ABH)
* Intel (R) Core(TM) i5-4590 CPU @ 3.30GHz
* 8GB DDR 3 RAM
* OS: Ubuntu 22.04 LTS
* KERNEL: Linux 5.15.0-70-generic
* Architecture: x86-64
