### ISSUE TITLE
Container slows down & grinds to a halt randomly

### ISSUE THREAD

**Issue by Sloth-on-meth** [linuxserver/docker-xbackbone#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Consistent performance 

## Current Behavior
container stops working after some time - sometimes minutes, sometimes longer.
uploads via shareX stop working.
container webUI gives 502 errors.
lots of IO by 'nginx worker process' processes, even when idle

## Steps to Reproduce

1.start container
2.wait
3.
4.

## Environment
**OS:** Ubuntu 21
**CPU architecture:** 64 bit 
**How docker service was installed:** docker-compose

## Command used to create docker container (run/create/compose/screenshot)
```
  xbackbone:
    image: lscr.io/linuxserver/xbackbone
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
#      - PHP_POST_MAX_SIZE=2000M
#      - PHP.POST.MAX.SIZE=1G
#      - upload_max_filesize=2000M
#      - PHP_UPLOAD_MAX_FILESIZE=2000M
    volumes:
      - /mnt/drive4/docker/xbackbone:/config
    ports:
      - 80
      - 443
    restart: unless-stopped
    networks:
      - web
      - internal
    restart: unless-stopped
  snapdrop:
    image: lscr.io/linuxserver/snapdrop
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/drive4/snapdrop:/config
    ports:
      - 80
      - 443
    restart: unless-stopped
    networks:
      - web
      - internal
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
